Output help by default

diff --git a/api/bash/pretty-print b/api/bash/pretty-print
--- a/api/bash/pretty-print
+++ b/api/bash/pretty-print
@@ -2,8 +2,17 @@
 
 # set -x # for debugging
 
-
-GH_TOKEN=""
+# TODO replace with plumbing
+gh_request()
+{
+  local gh_request_route=$@
+  if [ -n "$GH_TOKEN" ]
+  then
+    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json" -H "Authorization: token $GH_TOKEN"
+  else
+    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json"
+  fi
+}
 
 #### COLORS & FORMATTING
 
@@ -25,23 +34,58 @@ _target=${_magenta}
 _em=${_blue}${_bold}
 
 
-#### CORE FUNCTIONS
+##### META 
 
-gh_request()
+dependency_test()
 {
-  local gh_request_route=$@
-  if [ -n "$GH_TOKEN" ]
-  then
-    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json" -H "Authorization: token $GH_TOKEN"
-  else
-    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json"
-  fi
+  for dep in curl jq ; do
+    command -v $dep &>/dev/null || { echo -e "\n${_error}Error:${_reset} I require the ${_command}$dep${_reset} command but it's not installed.\n"; exit 1; }
+  done
 }
+
+usage()
+{
+  echo -e "Usage: $0 [options] <argv>...\n"
+  echo "Options:"
+  echo " -f | --forks <user/repository>   Display fork details"
+  echo " -r | --repo  <user/repository>   Display repo details"
+  echo " -u | --user  <username>          Display user details"
+  echo " -t | --token <token>             Set a GitHub token"
+  echo " -h | --help                      Help"
+  echo ""
+}
+
+
+#### HELPERS - to reduce duplication
+
+set_user_context()
+{
+  context=$(echo "$1" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's#/$## ')
+}
+set_repo_context()
+{
+  context=$(echo "$1" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's/\.*git$//' -e 's#/$##')
+}
+
+print_header(){
+
+  local name_length=${#context}
+  local header_length=$(( name_length + 13 ))
+  
+  echo -e "\nDetails for ${_target}$context${_reset}:"
+  for i in $(seq 1 $header_length); do
+    echo -n "="
+  done
+  echo -e "\n"
+  
+}
+
+#### CORE FUNCTIONS
 
 api_request()
 {
   local api_request_result=$( gh_request "$1") # only make a single API request
-  shift
+  shift # Shift 
 
   api_request_filtered=() # initialize/empty filtered results array
 
@@ -66,50 +110,33 @@ api_request_forks() # FIXME: refactor this into the main api_request function
 
 }
 
-dependency_test()
-{
-  for dep in curl jq ; do
-    command -v $dep &>/dev/null || { echo -e "\n${_error}Error:${_reset} I require the ${_command}$dep${_reset} command but it's not installed.\n"; exit 1; }
-  done
-}
-
-usage()
-{
-  echo -e "Usage: $0 [options] <argv>...\n"
-  echo "Options:"
-  echo " -u | --user <username>           Display user details"
-  echo " -r | --repo <user/repository>    Display repo details"
-  echo " -h | --help                      Help"
-  echo ""
-}
 
 #### FORMATTED REQUEST FUNCTIONS
 #    Uses format: `api_request 'API_ROUTE' 'FILTER1' 'FILTER2' ...`
 
 user_details()
 {
-  local cleaned_username=$(echo "${username}" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's#/$## ')
-  echo -e "\nDetails for GitHub user ${_magenta}$cleaned_username${_reset}:"
-  local name_length=${#cleaned_username}
+  print_header 
+
+  local name_length=${#context}
   local header_length=$(( name_length + 25 ))
-  for i in $(seq 1 $header_length); do
-    echo -n "="
-  done
-  echo -e "\n"
-  api_request "users/$cleaned_username" '.name' '.location' '.email' '.bio' '.public_repos' '.public_gists' '.followers' '.following' '.created_at'
+  
+  api_request "users/$context" '.name' '.location' '.email' '.bio' '.public_repos' '.public_gists' '.followers' '.following' '.created_at'
+
   echo "     Name: ${api_request_filtered[0]}"
   echo " Location: ${api_request_filtered[1]}"
   local email=${api_request_filtered[2]}
+  local bio=${api_request_filtered[3]}
+  local user_since=${api_request_filtered[8]}
+  
   if [ $email != "null" ]; then
     echo "    Email: $email"
   fi
-  local bio=${api_request_filtered[3]}
   if [ "$bio" != "null" ]; then
     echo "      Bio: $bio"
   fi
   echo -e "\n"
-  echo -e " ${_magenta}$cleaned_username${_reset} has shared ${_em}${api_request_filtered[4]}${_reset} public git repositories and ${_em}${api_request_filtered[5]}${_reset} gists.\n"
-  local user_since=${api_request_filtered[8]}
+  echo -e " ${_magenta}$context${_reset} has shared ${_em}${api_request_filtered[4]}${_reset} public git repositories and ${_em}${api_request_filtered[5]}${_reset} gists.\n"
   for i in $(seq 1 $name_length); do
     echo -n " "
   done
@@ -123,26 +150,26 @@ user_details()
 
 repo_details()
 {
-  local cleaned_repo=$(echo "${repo}" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's/\.*git$//' -e 's#/$##')
-  echo -e "\nDetails for repository ${_target}$cleaned_repo${_reset}:"
-  local name_length=${#cleaned_repo}
-  local header_length=$(( name_length + 24 ))
-  for i in $(seq 1 $header_length); do
-    echo -n "="
-  done
-  echo -e "\n"
-  api_request "repos/$cleaned_repo" '.name' '.owner.login' '.description' '.forks_count' '.stargazers_count' '.open_issues_count' '.created_at' '.updated_at' '.parent.name' '.parent.owner.login' '.clone_url' '.homepage'
-  echo -e " ${_bold}${_white}${api_request_filtered[0]}${_reset} by ${api_request_filtered[1]}\n"
+  print_header 
+
+  api_request "repos/$context" '.name' '.owner.login' '.description' '.forks_count' '.stargazers_count' '.open_issues_count' '.created_at' '.updated_at' '.parent.name' '.parent.owner.login' '.clone_url' '.homepage'
+
   local description=${api_request_filtered[2]}
+  local created_at=${api_request_filtered[6]}
+  local updated_at=${api_request_filtered[7]}
+  local parent_name=${api_request_filtered[8]}
+  local parent_owner=${api_request_filtered[9]}
+  local homepage=${api_request_filtered[11]} # FIXME: dirty hack because GH returns an empty value instead of null
+
+  echo -e " ${_bold}${_white}${api_request_filtered[0]}${_reset} by ${api_request_filtered[1]}\n"
   if [ "$description" != "null" ]; then
     echo " $description" | fmt
     echo ""
   fi
-  local homepage=${api_request_filtered[11]} # FIXME: dirty hack because GH returns an empty value instead of null
   if [[ -n $homepage ]]; then
     echo " Homepage: $homepage"
   fi
-  echo -e "\n ${_target}$cleaned_repo${_reset} has been forked ${_em}${api_request_filtered[3]}${_reset} times and starred ${_em}${api_request_filtered[4]}${_reset} times.\n"
+  echo -e "\n ${_target}$context${_reset} has been forked ${_em}${api_request_filtered[3]}${_reset} times and starred ${_em}${api_request_filtered[4]}${_reset} times.\n"
   for i in $(seq 1 $name_length); do
     echo -n " "
   done
@@ -150,11 +177,7 @@ repo_details()
   for i in $(seq 1 $name_length); do
     echo -n " "
   done
-  local created_at=${api_request_filtered[6]}
-  local updated_at=${api_request_filtered[7]}
   echo -e "  was created on ${_em}${created_at:0:10}${_reset} and last updated on ${_em}${updated_at:0:10}${_reset}."
-  local parent_name=${api_request_filtered[8]}
-  local parent_owner=${api_request_filtered[9]}
   if [ $parent_name != "null" ]; then
     echo -e "\n\n ${_target}${api_request_filtered[0]}${_reset} was forked from ${_yellow}$parent_name${_yellow} by ${_yellow}$parent_owner${_reset}"
   fi
@@ -165,25 +188,26 @@ repo_details()
 
 list_forks()
 {
-  local cleaned_repo=$(echo "${repo}" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's/\.*git$//' -e 's#/$##')
-  echo -e "\nDetails for repository ${_target}$cleaned_repo${_reset}:"
-  local name_length=${#cleaned_repo}
-  local header_length=$(( name_length + 24 ))
-  for i in $(seq 1 $header_length); do
-    echo -n "="
-  done
-  echo -e "\n"
-  api_request "repos/$cleaned_repo" '.name' '.owner.login' '.forks_count'
+  print_header 
+
+  api_request "repos/$context" '.name' '.owner.login' '.forks_count'
   echo -e "${_bold}${_white}${api_request_filtered[0]}${_reset} by ${api_request_filtered[1]}\n"
-  echo -e "\n${_target}$cleaned_repo${_reset} has been forked ${_em}${api_request_filtered[2]}${_reset} times, including forks by these GitHub users:\n"
-  api_request_forks "repos/$cleaned_repo/forks"
+  echo -e "\n${_target}$context${_reset} has been forked ${_em}${api_request_filtered[2]}${_reset} times, including forks by these GitHub users:\n"
+  api_request_forks "repos/$context/forks"
   echo -e "${_blue}$response${_reset}"
   echo ""
 }
 
+
 #### MAIN
 
 dependency_test
+
+# Print help if no params are passed.
+if [ -z $1 ]; then
+  usage
+  exit 1
+fi
 
 while [ "$1" != "" ]; do
   case $1 in
@@ -192,13 +216,14 @@ while [ "$1" != "" ]; do
     -t | --token )  shift
                     GH_TOKEN="$1" ;;
     -u | --user )   shift
-                    username="$1"
+                    set_user_context "$1"
+                    echo "Context is $context"
                     user_details ;;
     -r | --repo )   shift
-                    repo="$1"
+                    set_repo_context "$1"
                     repo_details ;;
     -f | --forks )  shift
-                    repo="$1"
+                    set_repo_context "$1"
                     list_forks
                     exit ;;
     * )             usage
