Update scripts/git-find-large-files
Co-authored-by: Lars Schneider <larsxschneider@github.com>

diff --git a/scripts/git-find-large-files b/scripts/git-find-large-files
--- a/scripts/git-find-large-files
+++ b/scripts/git-find-large-files
@@ -22,7 +22,7 @@
 if [ -z "$1" ]; then
     MIN_SIZE_IN_KB=500
 elif ! [[ "$1" =~ ^[0-9]+$ ]]; then
-    echo "Error: Expecting Integer Value" >&2; 
+    echo "Error: Expecting Integer Value" >&2
     echo " Usage: $0 [MIN_SIZE_IN_KB]"
     exit 1
 else
